baseurl = "http://example.org"
title = "遺言書"
author = "Joe Hutchinson"
canonifyurls = true
paginate = 5
theme = "aether"

[params]
brand = "Testament"
description = "aether Hugo theme for blogs"
bgimg = "img/ignasi_pattern_s.png"
