baseurl = "https://blog.himanoa.net"
title = "遺言書"
author = "himanoa"
canonifyurls = true
paginate = 5
theme = "aether"

[params]
brand = "Testament"
description = "ひまのあのブログです"

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', 'asciidoctor']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
  [security.funcs]
    getenv = ['^HUGO_']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
