---
title: "日記 2021-06-15"
date: 2021-06-16T00:12:51+09:00 
draft: false
author: himanoa
---

== ダイエット

昨日日記を書いた後散歩して、友達と通話をしながら朝を迎えた

今日は筋肉痛がひどすぎるのと徹夜なので寝る

== ちゃんとしたPR

ちゃんとしたPRってなんだろう。テンプレートだけではまともなPRっていうのはわからないので、OSSのPR一日一個を読むみたいなのをやってみたら言語化できるんじゃないか？という仮説をたてた

明日からやっていきたいがそこまでの余力があるのか果たして…

== 労働

無限に一つのコンポーネントのバグを取っていた。とりあえず手を入れてたコンポーネント自体はできたので繋ぎ込んで終わり

== React

* https://github.com/reactwg/react-18/discussions/18[How to support strict effects · Discussion #18 · reactwg/react-18]
* https://github.com/reactwg/react-18/discussions/21[Automatic batching for fewer renders in React 18 · Discussion #21 · reactwg/react-18]
* https://github.com/reactwg/react-18/discussions/41[New feature: startTransition · Discussion #41 · reactwg/react-18]

あたりをさらっと読んだ。

`startTransition` に関しては業務で使ったら若干便利そうなところをあるので導入したさがある。

ただ Concurrent modeをoptinするのかどうかの議論は必要そうだなーって感じ

`useEffect` の周りの話は最初見た時は使ってる箇所とマイグレーション方法的を考えた時に手間がやばいな…っておもったが、

[source,typescript]
----
import { useEffect, useRef } from 'react'

type OnUnmounted = () => void | void 

type UseWillBeMounted = (effect: () => OnUnmounted) => void

export const useWillBeMounted: UseWillBeMounted = (effect) => {
  const effectRef = useRef<boolean>(false)

  useEffect(() => {
    if(effectRef.current === false) {
      effectRef.current = true
      return effect()
    }
  }, [])
}
----

みたいなのを作って、 `eslint` ルールで +
`useEffect` を↑を使う形に置換する `autifixer` を書けば機械的にできそうだなあとおもった。

Automatic batchingに関しては一つのハンドラで複数回 `setState` するようなハンドラや状態は筋が悪いのでは？と考えていて、これが入っても別にあんまり便利ではないのでは？とおもった

== Jotai

久々に調べた。recoilのより楽なインターフェースライブラリっぽい。jotaiのAPIを使ってデータアクセスを書くと依存グラフがうまいこと形成されて、reselect的なアプローチをしなくても再レンダリングの最適化ができるよねみたいな認知をした。

むかしフォームライブラリを自作した時に変数参照が発生したら、依存関係に追加して依存先が更新されたら更新する、みたいなのを書いたことがあったので、スッと入ってきやすかったなとおもった。

↑をJotai使って作り直すのはおもしろそうだなとおもった

== FF14

零式消化をやった。二層でアンブラルオーブ二回くらいミスったりしたので、もう一回練習して体に叩き込んでおきたいなっておもった。


