---
title: "近況"
date: 2023-05-06T23:57:21+09:00 
draft: false
author: himanoa
---

もう半年くらいブログ書いてないことに気づいて緊急でブログ回しています！

というわけでいつもの近況報告。この時点で何を書くかまじで決めていない。

一応ロックマンエグゼ6のネタバレがあるので嫌なら見ないほうがいい

== ロックマンエグゼアドバンスドコレクション

4月に発売されたのは知っていたが仕事が忙しかったり、忙しかった反動でダウンしていた感じでプレイを始めたのは実は5/3とかだった。

とりあえず思い出深いエグゼ6のグレイガ版を1日でクリア。

最近自我を犠牲にしていたため、小学生当時にハマったものをやり直すと自我が取り戻せる感じがした。

最後にプレイしたのが小学生だったっていうのもあって今やると当時と違う感覚になるストーリーだった。

作中では「運命なんて言って無理している」や「運命ではなく私自身の意思だ！」といったセリフ回しが存在し、久々にやった中では一番気に入った。

社会で生きていると自分自身の意思を持ち続けることが大変しんどい局面があるが臆せず貫いていきたいなとおもった。

また、シリーズの最終作ということもあってクリア後に熱斗たちの20年後の話が語られる。

その中で作中デリートされた二体のナビが同じ名前の別プログラムとして、更生した悪役によって作り直されインターネットの治安を守っているという話があり、ソフトウェアだからできる輪廻転生を感じた。

あんまりネタバレしたくないので詳細は書かないが、ストーリーがストーリーだっただけに中々涙腺に来る展開だったし、自分が作るプログラムにはちゃんと気持ちを込めて名前を付けてあげたいなとおもえた

2000-2006年の作品なのに作者のインターネットやプログラムというものに対する理解度がとても高く沢山の時間が経過しても楽しめる作品だった。

社会人として、プログラマーとしてこの作品を遊ぶことで小学生の時とは見え方が違う物が沢山あった。

クリアしたのはエグゼ6だけなので、他の作品はまだである。対戦とかもする気は今のところないのでのんびり楽しんでいきたい。

エグゼ6といえばアイリスというキャラクターがとても性癖なのだが、とてもでかいネタバレ要素になることや感情が高まりすぎてまとまって話せないのでこの場では一旦割愛させていただく。ロックマンエグゼ6をクリアしたマンで飲みなり飯なり言って思う存分話したいよね。

== 掃除

気づけばゴミ袋は部屋に散乱し、髪の毛は床に落ちていて…みたいな限界生活だったのでさすがにこれはやばいとおもって生活を立て直すべくゴミ捨てや掃除をガッツリやった。

その結果裸足で歩いても何も付かず快適な生活になった。しかし、掃除が完了して綺麗さっぱりした後はどうも孤独感を強く感じるようになり、一人暮らしの生活が荒れやすいのは荒れた生活は孤独を癒やす魔力があることに起因するのでは？という仮説を立てるなどしていた。

掃除に関しては見える部分は大体終わったのだが、押し入れの中に入れたダンボールのゴミを片づけてないので明日はそれらを片づけたい

== 料理

最近できていない。生活の立て直し的に明日やることになりそうだ
