---
title: "自己紹介"
date: 2024-01-15T18:11:10+09:00 
draft: true
author: himanoa
---

某所で自己紹介が流行っているらしいので僕も便乗して書いてみる

== 名前

ひまのあといいます。ID名としてはhimanoaをよく使っていますが、IDを確保できないサービスではh1manoaを使うことがおおいです

ハンドルネームの由来は、由来らしい理由はなくて、小学生くらいの時にハンドルネームが必要になった時にハンドルネームジェネレーターから生成された名前を今の今まで使用しています

昔は一意性が高くて便利な名前だったのですが、VTuber文化が流行るにつれて一意性が担保されにくくなってきました。女の子の名前として「\^ひま.+」と「\^のあ」が使われやすいからですね。この二人が絡むとカップリング名は「ひまのあ」になってしまうからです。頼むからのあちゃん左固定になってくれ

== 趣味

=== プログラミング

興味の移り流行りが激しく雑食性が高いです。現状結構長続きしている趣味は「プログラミング」、「ゲーム」、「料理」、「ダーツ」です。

プログラミングは自分が使う小物プログラムを作るのが好きです。なんか下のようなものを作ったりしています

- https://github.com/himanoa/mkrepo[mkrepo]
  - gitリポジトリのディレクトリをghqのルールに基付いて作るツール
- https://github.com/himanoa/mdmg[mdmg]
  - 複数ファイル作る必要があるテンプレートファイルを単一のmarkdownで定義して、コマンド一撃でファイルを作ることができるCLIツール
- https://github.com/himanoa/goshiteki[goshiteki]
  - Vim上でGitHubのPRにレビューコメントできるツール
  - まじで最高のツールだった
  - diffを厳密に管理したかったがいい方法がおもいつかなかったのと、なんか動かなくなってしまったのでもう使ってない（◞‸◟）

デカいプロジェクトを一人で作ろうとして、仕事が忙しくなってエタった残骸がGitHubにあります。自己管理が終わっている弊害ですね。個人的には悩んでいるので誰かいい方法を教えてほしい（◞‸◟）

プログラミング言語だとRustとかTypeScriptが好きです。ただTypeScript、都合がいいだけであんまり言語機能として好きかどうかは怪しいです。人一倍詳しい自信はありますが…

Rustは好きだしまあそれなりーに書いてますが、めっちゃ詳しいわけじゃないです。最近はあんまり書けてないです。にわか

好きなtraitはRefCell Cell From

=== その他

PCゲームはいろいろします。最近はAC6とかをめっちゃやってますね。

昔はPvPばっかやってたんですが最近は血の気が収まってきてPvPじゃないモードのほうがよくやっている気がします。後雑食だから普通にゲームうまい人に勝てないし勝てるまで研鑽が積めない

料理は一人暮らしはじめてからやりはじめました。最近はあまりできてない…後述する食でちょっと触れます

ダーツは家にダーツボードが設置されています。仕事の時間テンポが絶妙に悪い時とかに打ってますね。寒くなってきてから外に投げにいけてないのでひさびさに投げたい

== 生まれと育ち

神奈川県のめっちゃ西のほう(熱海とか近い)の田舎で生まれました。

父親がプログラマーだったこともあって、幼い頃からパソコンに触る機会がおおかったです。Windows 98のログインマネージャーがハングアップしたりエラー吐いて落ちたりしていてよく大泣きしていたことが記憶に残っています。

小学生に上がる頃にはNintendo DSなどのゲーム機というおもちゃとパソコンの二刀流でした。 https://www.dou-mori.com/bbs3/[おいでよ、どうぶつの森通信掲示板]に籠っていたり、放課後にニコニコ動画をみていたりしました。

中学生くらいになると奇跡的に回りにオタクコミュニティがあってそこに属していました。東方とかめっちゃハマっていたのもこの辺です。

東方はそこそこシューティングゲームやってました。地霊殿EXクリアしたりLunaちょっとやってたりしました。ただもう全然覚えてなかったりでノーマルすら最近怪しくなってきました。悲しいね

パソコンが好きだったので高専を進路に選んでちょっと都会のほうに引っ越したりもしました。このあたりから本格的にプログラミングをはじめたりもしましたね(最初にやったのはC言語で、このあたりで培ったメモリのメンタルモデルがあるおかげでRustとか結構馴染みやすかった)

ただし人間関係がうまくいかなかったため、3年の時に退学しました。退学は人生でいい経験になったとおもっており、嫌だったり将来性を感じられないのであればやめてリスクをのみつつ切り返すという考えを身に付けることができました。

== 仕事

都内でプログラマーをやっています。とはいえ週一でか出社はしていなくて後は家で仕事しているのですが…

コードを書くことが何よりも得意で、そういう時間を増やすような活動をしたりしがちです。

後は仕事でプログラミングを効率的にすすめるためにはどうすればいいのかを考えて、コードに適用したりすることが得意です。

具体的には次の通り

- ビルド時間の改善
- テストしやすいようなコードベースの提供

この職業、人によってエンジニアといったりプログラマーといったりしています。二つに厳密な違いがあるのか僕はよくわかっていないですが、

1. プログラミングが好きなこと
1. 逆張り

で自己のアイデンティティをプログラマーにおいていて、そう名乗っています

== 食

食べ物は肉料理や魚料理が結構好きです。

具体的には次のようなものがすきです。

- 鯖の味噌煮
- 豚肉で作った肉じゃが

自炊も余裕がある時はします。得意料理は卵焼きです.l

<iframe src="https://mstdn.maud.io/@himanoa/109829170866397344/embed" class="mastodon-embed" style="max-width: 100%; border: 0" width="400" allowfullscreen="allowfullscreen"></iframe><script src="https://mstdn.maud.io/embed.js" async="async"></script>

知っとくとお得な知識として卵焼きを上手く作るコツを書いておきます。大体次の二つを意識するとうまくいきます

- 卵液を混ぜる所
  - なるべく気泡を潰すように混ぜることです。卵液を切るみたいな操作を意識する
- 火入れ
  - 強火を使うとめっちゃ気泡ができて断面がきたなくなるので、弱火でしっかり時間を使って焼く

最近上げてないですが、mastodonに https://mstdn.maud.io/deck/tags/%E9%A3%AF%E3%81%AE%E3%81%82[#飯のあ]というタグで料理の写真を投稿してたりもしました

== 思想

基本的に理想厨です。

現実的な解決策よりかは理想的な状況をどうやって実現するかに時間を使いたいなとおもっています。

仕事の話をすると、早く作るよりも、良く作る方がよいとおもっていますし、良い物を早く作るというのを目指すべきだと考えています。

キーボードとかこだわったり、キーマッピングを試行錯誤しながら変更したりしているのはこのあたりが由来の趣味ですね。

あと一人でいる時間を作ることがよりよい人生を作るためには重要だと考えています。

一人の時間を作ることで、自分が考えているモヤモヤを言語化するのに集中して時間を使ったり、自分という存在のために時間を使うことができるからです。これがあることで自己肯定感や他人と会話するときに、自信をもつことができるような気がしています
