---
title: "AC6のランクマでAランクまで到達したので諸々書こうとおもう"
date: 2024-01-15T21:01:29+09:00 
draft: false
author: himanoa
---

AC6のランクマ、ちまちまやってたらランクAまで来たので自分がやっていること、できていないことをまとめようかなとおもいます。

== やっていること

=== メタの把握

動画や上位勢の言っていることを鵜呑みにすると大体メタ読み間違えます。

そこで実際に潜って3-5戦ほど試しに潜ってみて、今の時間帯はこういうアセンがおおいなーみたいな傾向を考えてそれに勝てるようなアセンを作ることがおおいです。

具体的には次のような感じで使うアセンを決めたりしています。

==== 1. 5戦くらい潜る

この時1マッチ1マッチ間髪入れて潜ると同じ人に当たる可能性が極めて高いのでディレイを入れながら潜るといろいろな人と当たれて便利です。

勝ち負けはあんまり気にしなくてよいです。このゲームはアセンじゃんけんな側面がかなり強くて、マッチング時点で勝負が決まっていることが多々あります。この段階で負けても怒らないようにしましょう


5戦だと明確なメタを読むことはできませんが、まあころころ変わるようなものなのであんまり時間かけてもうまくいきません。適度に切り上げて次の作業に入りましょう。

メタが当たってたらポイントが盛れるし、外れてたらポイントが下がるだけの話です

==== 2. 大まかな傾向を掴む

5戦くらい潜ったらおおまかな傾向について考えます。
例えば当たったアセンの内訳が次のようだったと過程してここでは物事を説明します

1. ニドスラ軽2
1. ニドスラ中2
1. 重ショAB重2
1. EARSHOT搭載重2
1. ガチタン 

こういったマッチだった時は、次のようなことを意識していきます。

==== 3. 考察とアセン決め


- 戦法が近接に偏りすぎている
- 引きミサイラー & ライフル引き撃ち & タンクが少ない

これらの情報を使って自分なりの考察をしていきましょう

- 戦法が近接に偏りすぎている
  - ABが強い環境になっている。直前の勝ちアセンは引きランセツだったとかかな？
- 引きミサイラーやライフル引き撃ち、タンクが少ない
  - 勝てなさすぎて駆逐された or これらに勝ちすぎて上に上がったので今のランクではマッチしなくなった

ここまでで状況の考察はうちきって自分の主観を考察に入れていきます。

1. ニドスラシリーズはDPSがLCB搭載のガチタンに勝てない。
1. 重ショABはLCB搭載ガチタンに勝てない
1. EARSHOT系列はLCB搭載ガチタン目線でちょい不利目だが返せないこともない

よってLCBタンクは勝ち切って上に登っていそうな環境だということがなんとなく想像が付きます

引きミサイラーも同様に重ショ以外には割と有利な感じがするので大丈夫そう。

ライフル引き内に関しては、AB凸に弱くニドスラにもブレホ凸で崩されてそのまま即死しやすい、ガチタンは距離減衰の都合上何かしら当たる距離を維持し続けないといけない ことを考えると負けアセンっぽいことがわかります

というわけでPSが少なく扱いやすい、LCBタンクを使うことを決定

みたいなことを考えてやっています

=== 負けたアセンを試す

ゲームしてみて相手が使っていたアセンは積極的に試しましょう。強み弱みを把握することによってメタ読みした後に使う機体の手札を増やすことができます。

また、似たようなアセンとたたかった時の弱点もわかりやすいのでポイントを溶かしてでもやったほうがいいとおもいます。

ゲームを上手くなるうえで知識量を増やすというのはやったほうがいいので…

== できてないこと

=== 地形戦

地形を使ってダメージを減らし、一方的に相手にミサイルを当てることによってAP差を作ってタイムアップで勝つ戦法です。旧作ACでよくあるやつですね。

Aランクまではこういう手を使ってくる人があんまりいなくて、僕はやらずにAまできましたが、Aからはこれをやってくる人が増えている印象があります。

というわけで僕も最近これを練習したりYoutubeで動画見て知識を付けたりしています

=== 一つのアセンの練度上げ

やってないです。ただ、勝ち続けるならやったほうがいいなとおもいます。時間が足りないねえ
