---
title: "2023年再考"
date: 2024-02-03T08:36:45+09:00 
draft: false
author: himanoa
---

2023年について考えてみるといろいろおもうことがあったのでメモがてら残しておく。なんというか人に読ませる文章ではないのでとっちらかっているかもしれない

== 労働

今年やっていたこと、できなかったこと

=== アーキテクト

巨大モノリスSPAの分割。

長年の開発月日によって巨大なモノリスになってしまったアプリケーション、業務システムということもありバンドルサイズに無関心に開発をしていたらバンドルサイズはどんどん肥大化し、webpackのスピンアップコストも肥大化し、CIのビルドタスクで必要なメモリもおおくなってしまいとんでもない状況になってしまった。

こういった問題をどうやって解決するかを考える仕事をした

古いコードから新しいコードに変える必要も多々あり、migration用のESLintルールを多数開発したり、密結合のアプリケーションから個別パッケージにソースコード単位で安全にcloneするツールを作ってmigration作業をしていた

https://github.com/himanoa/dependencies-based-clone[つくったやつ]

=== コミュニケーション

明確にできなかった。人に仕事を任すのが単純に下手だった。

具体的に発生した問題はつぎの通り

* 他人の出力が自分の期待した物ではない
* 闇に葬りさられる

その結果一人で仕事する時間が圧倒的に増え、やっている仕事のインパクトというのが薄れてしまった。インパクトが薄れることによって並列で別の改修が走ったり困る実装が知らない意思決定プロセスから生えて常に頭を悩まされる状態に置かれることになった

どうすればよかったか、というのは今だによくわからない。上司ともこの話はよくしている気がするがどの提案も納得できなかった。

人を巻き込むためにコミュニケーションをもっと取ったほうがいい、という話はごもっともだが提案してもレスポンスがこないからどうやってコミュニケーションを深めるんだ、という観点で疑問が残っている

そもそも、一人で全部草案作ったのがよくなかったんじゃないかなみたいな観点もある

全体周知という形で共有したりタスク任せたりしたのがよくなかったかもしれない、もっと個別にやるのが正しいアプローチだったのかも。これは検証の余地あるなとおもっていて、最近そういう仕事のやり方を意識している。具体的には、とりあえず全体周知が必要なものに関してはマネージャーに全部相談して適切な人間を割り当ててもらって、そこを全部通す形にするみたいな。まあ意図的ではない部分が過多でマネージャーにだっこされているはある

== 生活

一番おおきなライフスタイルの変化はTwitterをやめたことだ。

代替としてmastodonに移行はしたが、見る頻度は以前Twitterみていた頻度とは比べものにならないほどmastodonもみてないし投稿もしていない。

Twitterをやめた理由は色々あるが、TLみて不快に感じることが増えた。プライベートな時間でストレスを作るのは人生を無駄にしている感じがあったというのが一番おおきな理由である。

やめて浮いた時間で何かはじめたか、というとそういうわけでもない。部屋でダーツしたり考え事をしたり、Discordで人と話してたり見ている時間が増えただけだ。

これによって気づいたことや良かったこと、悪かったことがいろいろあるので、ここではそれらについて語っていこうとおもう

=== 良くなかったこと

あまり明瞭ではない。

[start=1]
. 元々世間知らず、トレンドに疎い状態だったが自分が興味あることですら疎くなった
. 交友関係が減った
. あらゆる物事への興味関心が薄れた。
. Twitterをやっている人間に対しての選民思想

これらによって、世界と自分が切り離されたような感覚を感じることはTwitterをやめる以前より増えた気がする。

また、今まではよくもわるくも世界的なトレンドはこうだから、みたいな論調で考えていた部分がまったくなくなった。自分が正しいとおもったからこうしています。なぜ正しいと思うかは〜という考え方にシフトしていっている気がする。

他人とコラボレーションして物事を進めるという考え方が自分の中からどんどん欠落していっている気がする。これの何がよくないかが明確にわからないのもよくない気がする。

言語化できない危機感を常に感じている

=== 良かったこと

[start=1]
. (程度はあるが)今でも交友している人間とはより深い仲になった気はする
. 不幸な事故ニュースによって悲しい気持ちになることがなくなった
. 思考停止できていた部分が少なくなった
. 本を読むということができるようになった

メンタル面はかなり安定するようになった気がする、とはいえリアルでヘコむようなことがあれば相応にヘコむので本質的は何も変わっていないのだが…

前より考える時間が増えたのは人生が豊かになった感じがしてよいなとおもった。

個人的には本を読むようになったのが結構良かった。

本という媒体はすごくて、なんとオーバーレイ広告がでないし情報が正確でまとまっていることがあり、知識として役に立ちやすくて神

=== Twitterをやめることで気づいたこと

* インターネット検索という機能はもう完全に汚れ切っており、あれを使って常日頃欲しい情報にアクセスするのは困難だということ。
** Twitterにしかない情報というのは案外多い
** 知識をストックで保持してインターネットに公開することへの価値が、低下していったのだろう
*** 文書という媒体が衰退して動画になっただけのような気もするが…
*** Youtube shortなどもでてきており、動画もフロー情報化しているように思えるから、ストック情報として保持することに人々が関心を持たなくなったのだろう。
*** 俺も最近よりブログを書かなくなった気がする


== 最後に

なんか統合失調症になりそうな気がしてこわいなぁと感じています。

他にも

* 自分の人格に自信がなくなってきたこと
* 人格を矯正しないとこの先社会でやっていけなさそうな感覚があること
* 自分が好きだったpublic communicationがメインな社会というのは幻想だったのかもしれないと思っていること

などいろいろ書きたいことはあるのですが、まとまりがなさそうなのでまたの機会に書くか、お蔵入りにしようとおもいます。

去年もつらい1年でしたが今年も好転する兆しがまったく見えないですね。人生はいつも厳しい
