defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: monachus/hugo

version: 2.1
jobs:
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: pwd
      - run: echo $USERNAME
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Hugo Version Check
          command: hugo version
      - run: rm -rf public
      - run:
          name: Git Clone
          command: git clone --depth 1 https://himanoa:$GITHUB_TOKEN@github.com/himanoa/testament public
      - run:
          name: Hugo Build
          command: hugo --minify
      - run: cd public && pwd
      - run: cd public && git config user.email "matsunoappy@gmail.com"
      - run: cd public && git config user.name "himanoa"
      - run: cd public && git add -A
      - run: cd public && git commit --allow-empty -m "[ci skip] deploy from CI"
      - run: cd public && git push origin master

workflows:
  version: 2.1
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
