defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: monachus/hugo

version: 2.1
jobs:
  deploy:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c3:75:55:31:72:4f:8e:87:94:b3:f8:22:4a:1e:94:f9"
      - checkout
      - run: pwd
      - run: echo $USERNAME
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Hugo Version Check
          command: hugo version
      - run: rm -rf public
      - run:
          name: Hugo Build
          command: hugo --minify
      - run:  pwd && ls
      - run:  git config user.email "matsunoappy@gmail.com"
      - run:  git config user.name "himanoa"
      - run:  git add -A
      - run:  git remove add upstream git@github.com:${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git
      - run:  git commit --allow-empty -m "[ci skip] deploy from CI"
      - run:  git push upstream master

workflows:
  version: 2.1
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
