version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: cibuilds/hugo:0.80
    working_directory: ~/hugo
    steps:
      - run:
          name: Update enviroment
          command: apt-get update && apt-get install git
      - run:
          name: Install asciidoctor 
          command: apt-get install asciidoctor
      - run:
          name: Hugo version
          command: echo "$(hugo version)"
      - checkout
      - run:
          name: git submodule initialize
          command: |
            git submodule init
            git submodule update
      - run:
          name: Building blog pages
          command: |
            HUGO_ENV=production hugo
            cp public/index.xml public/feed.xml
      - add_ssh_keys:
          fingerprints:
            - "c3:75:55:31:72:4f:8e:87:94:b3:f8:22:4a:1e:94:f9"
      - deploy:
          name: Deploy to GitHub Pages
          command: ./.circleci/deploy.sh
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: monachus/hugo

