version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    steps:
      - run:
          name: Update enviroment
          command: apk update && apk add git
      - run:
          name: Hugo version
          command: echo "$(hugo version)"
      - checkout
      - run:
          name: Building blog pages
          command: |
            HUGO_ENV=production hugo -v
            cp public/index.xml public/feed.xml
      - add_ssh_keys:
          fingerprints:
            - "fb:57:17:42:ad:d1:ce:16:4c:a9:86:2f:92:15:d9:32"
      - deploy:
          name: Deploy to GitHub Pages
          command: ./.circleci/deploy.sh
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: monachus/hugo

